import React,{useEffect,useMemo,useState}from'react';
import{Lock,ChevronLeft,LogOut,Check,History as HistoryIcon}from'lucide-react';
import{supabase}from'./supabase';
const TYPES={win:{label:'Wygrana',points:3,icon:'🟢'},draw:{label:'Remis',points:1,icon:'🟡'},loss:{label:'Porażka',points:0,icon:'🔴'}};
const today=()=>new Date().toLocaleDateString('sv-SE');
const datePL=v=>new Intl.DateTimeFormat('pl-PL',{day:'numeric',month:'long',year:'numeric'}).format(new Date(v+'T12:00:00'));
const avg=n=>Number(n||0).toLocaleString('pl-PL',{minimumFractionDigits:2,maximumFractionDigits:2});
export default function App(){
 const[screen,setScreen]=useState('ranking'),[sort,setSort]=useState('points'),[players,setPlayers]=useState([]),[matches,setMatches]=useState([]),[results,setResults]=useState([]),[session,setSession]=useState(null),[isAdmin,setIsAdmin]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
 const load=async()=>{setLoading(true);const[p,m,r]=await Promise.all([supabase.from('players').select('*').eq('active',true).order('stable_order'),supabase.from('matches').select('*').order('match_date',{ascending:false}),supabase.from('match_results').select('*')]);if(p.error||m.error||r.error)setMessage(p.error?.message||m.error?.message||r.error?.message);else{setPlayers(p.data);setMatches(m.data);setResults(r.data)}setLoading(false)};
 useEffect(()=>{load();supabase.auth.getSession().then(({data})=>setSession(data.session));const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(!session){setIsAdmin(false);return}supabase.from('admins').select('user_id').eq('user_id',session.user.id).maybeSingle().then(({data})=>setIsAdmin(!!data))},[session]);
 const ranking=useMemo(()=>players.map(p=>{const rows=results.filter(r=>r.player_id===p.id),points=rows.reduce((s,r)=>s+TYPES[r.result].points,0),played=rows.length;return{...p,points,played,average:played?points/played:0,wins:rows.filter(r=>r.result==='win').length,draws:rows.filter(r=>r.result==='draw').length,losses:rows.filter(r=>r.result==='loss').length}}).sort((a,b)=>{const keys=sort==='points'?['points','average','played']:sort==='matches'?['played','points','average']:['average','points','played'];for(const k of keys)if(b[k]!==a[k])return b[k]-a[k];return a.stable_order-b.stable_order}),[players,results,sort]);
 return <main className="app">{message&&<div className="alert">{message}</div>}{screen==='ranking'&&<Ranking data={ranking} sort={sort} setSort={setSort} setScreen={setScreen} session={session}/>} {screen==='login'&&<Login back={()=>setScreen('ranking')} success={()=>setScreen('admin')}/>} {screen==='admin'&&(session&&isAdmin?<Admin players={players} onDone={async()=>{await load();setScreen('ranking')}} logout={async()=>{await supabase.auth.signOut();setScreen('ranking')}} back={()=>setScreen('ranking')}/>:session?<Denied back={()=>setScreen('ranking')}/>:<Login back={()=>setScreen('ranking')} success={()=>setScreen('admin')}/>)} {screen==='history'&&<History matches={matches} results={results} players={players} back={()=>setScreen('ranking')}/>} {loading&&<div className="loading">Ładowanie…</div>}</main>}
function Ranking({data,sort,setSort,setScreen,session}){return <section className="page ranking"><h1>Ranking wtorkowej sali</h1><div className="segments">{[['points','Punkty'],['matches','Mecze'],['average','Średnia']].map(([v,l])=><button className={sort===v?'active':''} onClick={()=>setSort(v)} key={v}>{l}</button>)}</div><div className="list">{data.map((p,i)=><div className="row" key={p.id}><span className="pos">{i+1}</span><span className="name">{p.name}</span><span>{p.points}<small> pkt</small></span><span>{p.played}<small> mecz.</small></span><span>{avg(p.average)}</span></div>)}</div><div className="bottom"><button className="link" onClick={()=>setScreen('history')}><HistoryIcon size={14}/>Historia</button><button className="link" onClick={()=>setScreen(session?'admin':'login')}><Lock size={13}/>Admin</button></div></section>}
function Login({back,success}){const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[err,setErr]=useState('');const submit=async e=>{e.preventDefault();setErr('');const{error}=await supabase.auth.signInWithPassword({email,password});if(error)setErr('Nieprawidłowy e-mail lub hasło');else success()};return <section className="page"><button className="back" onClick={back}><ChevronLeft/>Wróć</button><div className="card login"><Lock/><h2>Logowanie administratora</h2><form onSubmit={submit}><input type="email" required placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" required placeholder="Hasło" value={password} onChange={e=>setPassword(e.target.value)}/>{err&&<p className="error">{err}</p>}<button className="primary">Zaloguj</button></form></div></section>}
function Admin({players,onDone,logout,back}){const[date,setDate]=useState(today()),[draft,setDraft]=useState({}),[saving,setSaving]=useState(false),[err,setErr]=useState('');const save=async()=>{const selected=Object.entries(draft).filter(([,v])=>v);if(!selected.length){setErr('Wybierz wynik co najmniej jednego uczestnika.');return}setSaving(true);const{data:match,error:e1}=await supabase.from('matches').insert({match_date:date}).select().single();if(e1){setErr(e1.message);setSaving(false);return}const rows=selected.map(([id,result])=>({match_id:match.id,player_id:Number(id),result}));const{error:e2}=await supabase.from('match_results').insert(rows);if(e2){await supabase.from('matches').delete().eq('id',match.id);setErr(e2.message);setSaving(false);return}await onDone()};return <section className="page admin"><header><button className="back" onClick={back}><ChevronLeft/>Ranking</button><button className="logout" onClick={logout}><LogOut size={14}/>Wyloguj</button></header><h1>Dodaj punkty</h1><p>Wyniki meczu</p><label>Data meczu</label><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><div className="players">{players.map(p=><div className="player" key={p.id}><b>{p.name}</b><div className="choices"><button className={!draft[p.id]?'none sel':'none'} onClick={()=>setDraft(d=>({...d,[p.id]:null}))}>⚪ Nie grał</button>{Object.entries(TYPES).map(([k,t])=><button className={`${k} ${draft[p.id]===k?'sel':''}`} onClick={()=>setDraft(d=>({...d,[p.id]:k}))} key={k}>{t.icon} {t.label}<small>+{t.points}</small></button>)}</div></div>)}</div><div className="summary"><b>Uczestnicy: {Object.values(draft).filter(Boolean).length}</b><span>🟢 Wygrane: {Object.values(draft).filter(v=>v==='win').length}</span><span>🟡 Remisy: {Object.values(draft).filter(v=>v==='draw').length}</span><span>🔴 Porażki: {Object.values(draft).filter(v=>v==='loss').length}</span></div>{err&&<p className="error">{err}</p>}<button className="primary sticky" disabled={saving} onClick={save}>{saving?'Zapisywanie…':'Zapisz wyniki'}</button></section>}
function History({matches,results,players,back}){return <section className="page"><button className="back" onClick={back}><ChevronLeft/>Ranking</button><h1>Historia</h1>{matches.length?matches.map(m=><div className="card match" key={m.id}><h3>{datePL(m.match_date)}</h3>{results.filter(r=>r.match_id===m.id).map(r=><div key={r.id}><span>{players.find(p=>p.id===r.player_id)?.name}</span><b>{TYPES[r.result].icon} {TYPES[r.result].label} +{TYPES[r.result].points}</b></div>)}</div>):<div className="card">Brak zapisanych meczów.</div>}</section>}
function Denied({back}){return <section className="page"><div className="card"><h2>Brak uprawnień</h2><p>To konto nie jest administratorem.</p><button className="primary" onClick={back}>Wróć</button></div></section>}
