import React,{useEffect,useMemo,useState}from"react";
import{ArrowLeft,Check,History as HistoryIcon,Lock,LogOut,Pencil,Trash2,X}from"lucide-react";
import{supabase}from"./supabase";
const TYPES={win:{label:"Wygrana",points:3,symbol:"✓"},draw:{label:"Remis",points:2,symbol:"−"},loss:{label:"Porażka",points:1,symbol:"×"}};
const today=()=>new Date().toLocaleDateString("sv-SE");
const datePL=v=>new Intl.DateTimeFormat("pl-PL",{day:"numeric",month:"long",year:"numeric"}).format(new Date(v+"T12:00:00"));
function statsFor(players,matches,results){const ordered=[...matches].sort((a,b)=>a.match_date.localeCompare(b.match_date)||Number(a.id)-Number(b.id));const last5=ordered.slice(-5);return players.map(p=>{const rows=results.filter(r=>r.player_id===p.id),map=new Map(rows.map(r=>[r.match_id,r]));return{...p,played:rows.length,points:rows.reduce((s,r)=>s+(TYPES[r.result]?.points||0),0),bibs:rows.filter(r=>r.took_bibs).length,form:last5.map(m=>map.get(m.id)?.result||null)}})}
export default function App(){const[view,setView]=useState({name:"ranking"}),[sort,setSort]=useState("points"),[players,setPlayers]=useState([]),[matches,setMatches]=useState([]),[results,setResults]=useState([]),[session,setSession]=useState(null),[admin,setAdmin]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[toast,setToast]=useState("");
async function load(){setLoading(true);const[p,m,r]=await Promise.all([supabase.from("players").select("*").eq("active",true).order("stable_order"),supabase.from("matches").select("*").order("match_date",{ascending:false}),supabase.from("match_results").select("*")]);const e=p.error||m.error||r.error;if(e)setError(e.message);else{setPlayers(p.data||[]);setMatches(m.data||[]);setResults(r.data||[])}setLoading(false)}
useEffect(()=>{load();supabase.auth.getSession().then(({data})=>setSession(data.session));const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
useEffect(()=>{if(!session){setAdmin(false);return}supabase.from("admins").select("user_id").eq("user_id",session.user.id).maybeSingle().then(({data})=>setAdmin(!!data))},[session]);
useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(""),2400);return()=>clearTimeout(t)},[toast]);
const stats=useMemo(()=>statsFor(players,matches,results),[players,matches,results]);const ranking=useMemo(()=>[...stats].sort((a,b)=>sort==="matches"?(b.played-a.played||b.points-a.points||a.stable_order-b.stable_order):(b.points-a.points||b.played-a.played||a.stable_order-b.stable_order)),[stats,sort]);
async function done(msg){await load();setToast(msg);setView({name:"admin"})}async function logout(){await supabase.auth.signOut();setView({name:"ranking"})}
return <main className="app">{error&&<div className="global-error">{error}<button onClick={()=>setError("")}><X size={14}/></button></div>}{view.name==="ranking"&&<Ranking data={ranking} sort={sort} setSort={setSort} history={()=>setView({name:"history"})} openAdmin={()=>setView({name:session?"admin":"login"})}/>} {view.name==="login"&&<Login back={()=>setView({name:"ranking"})} success={()=>setView({name:"admin"})}/>} {view.name==="admin"&&(session&&admin?<AdminHome matches={matches} results={results} back={()=>setView({name:"ranking"})} logout={logout} add={()=>setView({name:"edit"})} edit={id=>setView({name:"edit",id})}/>:session?<Denied back={()=>setView({name:"ranking"})}/>:<Login back={()=>setView({name:"ranking"})} success={()=>setView({name:"admin"})}/>)} {view.name==="history"&&<History matches={matches} results={results} players={players} admin={admin} back={()=>setView({name:"ranking"})} edit={id=>setView({name:"edit",id})}/>} {view.name==="edit"&&session&&admin&&<Editor players={players} match={matches.find(m=>m.id===view.id)} old={results.filter(r=>r.match_id===view.id)} back={()=>setView({name:"admin"})} done={done}/>} {loading&&<div className="loading">Ładowanie…</div>}{toast&&<div className="toast"><Check size={14}/>{toast}</div>}</main>}
function Ranking({data,sort,setSort,history,openAdmin}){return <section className="page ranking"><header><h1>Ranking wtorkowej sali</h1><p>Forma: pięć ostatnich terminów</p></header><div className="segments"><button className={sort==="points"?"active":""} onClick={()=>setSort("points")}>Punkty</button><button className={sort==="matches"?"active":""} onClick={()=>setSort("matches")}>Mecze</button></div><div className="head"><span>#</span><span>Zawodnik</span><span>Pkt</span><span>M</span><span>Forma</span></div><div className="rank-list">{data.map((p,i)=><div className={`rank-row top-${i+1}`} key={p.id}><span className="pos">{i+1}</span><div className="player-name"><span>{p.name}</span>{p.bibs>0&&<b className="z-badge" title={`Znaczniki: ${p.bibs}`}>Z{p.bibs>1&&<sup>{p.bibs}</sup>}</b>}</div><strong>{p.points}</strong><span>{p.played}</span><Form values={p.form}/></div>)}</div><nav className="bottom"><button onClick={history}><HistoryIcon size={14}/>Historia</button><button onClick={openAdmin}><Lock size={13}/>Admin</button></nav></section>}
function Form({values}){const list=[...Array(Math.max(0,5-values.length)).fill(null),...values];return <div className="form">{list.map((v,i)=><i className={`form-box ${v||"empty"}`} key={i}>{v?TYPES[v].symbol:""}</i>)}</div>}
function Login({back,success}){const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[err,setErr]=useState(""),[busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setBusy(true);const{error}=await supabase.auth.signInWithPassword({email,password});setBusy(false);if(error)setErr("Nieprawidłowy e-mail lub hasło");else success()}return <section className="page padded"><button className="back" onClick={back}><ArrowLeft size={17}/>Ranking</button><div className="card login"><Lock/><h2>Logowanie administratora</h2><form onSubmit={submit}><input type="email" required placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" required placeholder="Hasło" value={password} onChange={e=>setPassword(e.target.value)}/>{err&&<div className="err">{err}</div>}<button className="primary" disabled={busy}>{busy?"Logowanie…":"Zaloguj"}</button></form></div></section>}
function AdminHome({matches,results,back,logout,add,edit}){return <section className="page padded"><div className="nav"><button className="back" onClick={back}><ArrowLeft size={17}/>Ranking</button><button className="back" onClick={logout}><LogOut size={14}/>Wyloguj</button></div><h1>Panel administratora</h1><p className="sub">Dodawaj mecze, oznaczaj Z i poprawiaj historię</p><button className="primary full" onClick={add}>Dodaj nowy mecz</button><h3>Historia do edycji</h3><div className="history-list">{matches.map(m=><button key={m.id} onClick={()=>edit(m.id)}><span><b>{datePL(m.match_date)}</b><small>{results.filter(r=>r.match_id===m.id).length} uczestników</small></span><em><Pencil size={13}/>Edytuj</em></button>)}</div></section>}
function History({matches,results,players,admin,back,edit}){return <section className="page padded"><button className="back" onClick={back}><ArrowLeft size={17}/>Ranking</button><h1>Historia meczów</h1>{matches.length?matches.map(m=><article className="card match" key={m.id}><header><div><h3>{datePL(m.match_date)}</h3><small>{results.filter(r=>r.match_id===m.id).length} uczestników</small></div>{admin&&<button onClick={()=>edit(m.id)}><Pencil size={13}/>Edytuj</button>}</header>{results.filter(r=>r.match_id===m.id).map(r=><div className="history-row" key={r.id}><span>{players.find(p=>p.id===r.player_id)?.name}{r.took_bibs&&<b className="z-badge inline">Z</b>}</span><em className={r.result}>{TYPES[r.result].label} +{TYPES[r.result].points}</em></div>)}</article>):<div className="card">Brak meczów.</div>}</section>}
function Editor({players,match,old,back,done}){const[date,setDate]=useState(match?.match_date||today()),[draft,setDraft]=useState(()=>Object.fromEntries(players.map(p=>[p.id,old.find(r=>r.player_id===p.id)?.result||null]))),[bibs,setBibs]=useState(()=>new Set(old.filter(r=>r.took_bibs).map(r=>r.player_id))),[busy,setBusy]=useState(false),[err,setErr]=useState("");const count=Object.values(draft).filter(Boolean).length;function toggle(id){setBibs(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n})}async function save(){if(!count){setErr("Wybierz co najmniej jednego uczestnika.");return}for(const id of bibs)if(!draft[id]){setErr("Osoba oznaczona Z musi uczestniczyć w meczu.");return}setBusy(true);setErr("");let id=match?.id;if(match){let q=await supabase.from("matches").update({match_date:date,updated_at:new Date().toISOString()}).eq("id",id);if(q.error){setErr(q.error.message);setBusy(false);return}q=await supabase.from("match_results").delete().eq("match_id",id);if(q.error){setErr(q.error.message);setBusy(false);return}}else{const q=await supabase.from("matches").insert({match_date:date}).select().single();if(q.error){setErr(q.error.message);setBusy(false);return}id=q.data.id}const rows=players.filter(p=>draft[p.id]).map(p=>({match_id:id,player_id:p.id,result:draft[p.id],took_bibs:bibs.has(p.id)}));const q=await supabase.from("match_results").insert(rows);if(q.error){setErr(q.error.message);setBusy(false);return}await done(match?"Mecz poprawiony":"Mecz dodany")}
async function remove(){if(!match||!confirm("Usunąć cały mecz?"))return;setBusy(true);const q=await supabase.from("matches").delete().eq("id",match.id);if(q.error)setErr(q.error.message);else await done("Mecz usunięty")}
return <section className="page editor"><header><button className="back" onClick={back}><ArrowLeft size={17}/>Panel</button><div><h1>{match?"Edytuj mecz":"Dodaj punkty"}</h1><small>{count} uczestników</small></div></header><div className="editor-body"><label>Data meczu</label><input type="date" value={date} onChange={e=>setDate(e.target.value)}/>{err&&<div className="err">{err}</div>}<div className="players">{players.map(p=><div className="player-card" key={p.id}><div className="player-head"><b>{p.name}</b><button className={`z-toggle ${bibs.has(p.id)?"selected":""}`} onClick={()=>toggle(p.id)} title="Zabrał znaczniki">Z</button></div><div className="choices"><Choice active={!draft[p.id]} kind="absent" label="Nie grał" click={()=>{setDraft(d=>({...d,[p.id]:null}));setBibs(s=>{const n=new Set(s);n.delete(p.id);return n})}}/>{Object.entries(TYPES).map(([k,t])=><Choice key={k} active={draft[p.id]===k} kind={k} label={t.label} points={t.points} click={()=>setDraft(d=>({...d,[p.id]:k}))}/>)}</div></div>)}</div>{match&&<button className="delete" onClick={remove}><Trash2 size={14}/>Usuń mecz</button>}</div><div className="save"><button className="primary full" disabled={busy||!count} onClick={save}>{busy?"Zapisywanie…":match?"Zapisz poprawki":"Zapisz wyniki"}</button></div></section>}
function Choice({active,kind,label,points,click}){return <button className={`choice ${kind} ${active?"selected":""}`} onClick={click}><span>{label}</span>{points!==undefined&&<small>+{points}</small>}</button>}
function Denied({back}){return <section className="page padded"><div className="card"><h2>Brak uprawnień</h2><button className="primary full" onClick={back}>Wróć</button></div></section>}
